version: '3.5'
name: 'webmin'
services:
  webmin:
    container_name: webmin_master
    privileged: true
    build:
      context: ./
    volumes:
      - ../docker:/usr/share/webmin/docker:rw # This also requires the ACL permission to load in Webmin, see dockerfile
      - ./dind:/home/dind:rw
    ports:
      - "10000:10000"
    cap_add:
      - NET_ADMIN