# Sync changes to translations
name: Package release

on: # yamllint disable-line rule:truthy
  push:
    tags:
    - "**"

# Workflow jobs
jobs:
  # One job
  release:
    name: "Release"

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Required for release
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@master
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
            ./docker
          outPath: docker.wbm.gz

      # https://github.com/marketplace/actions/create-release
      - name: "Upload release"
        uses: ncipollo/release-action@v1
        with:
          artifacts: "docker.wbm.gz"
          tag: ${{ github.ref_name }}
          prerelease: true
          draft: true
          generateReleaseNotes: true