# Sync changes to translations
name: Package release

on: # yamllint disable-line rule:truthy
  # push:
  #   tags:
  #   - "**"
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to create
        required: true
        type: string
      draft:
        description: Create / update as draft
        default: true
        required: true
        type: boolean

# Workflow jobs
jobs:
  # One job
  release:
    name: "Release"

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Required for release
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@master
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
            ./docker
          outPath: docker.wbm.gz

      # Manual release
      # https://github.com/marketplace/actions/create-release
      - name: "Upload release"
        uses: ncipollo/release-action@v1
        with:
          artifacts: "docker.wbm.gz"
          tag: ${{ inputs.tag }} #${{ github.ref_name }}
          commit: main
          prerelease: true
          draft: ${{ inputs.draft }}
          generateReleaseNotes: true
          allowUpdates: true
          replacesArtifacts: true
          omitPrereleaseDuringUpdate: true
          omitNameDuringUpdate: true
